name: Deploy Next.js app to GitHub Pages

on:
  push:
    branches:
      - main
env:
    NOTION_TOKEN: ${{ vars.NOTION_TOKEN }}
    WORK_DATABASE_ID: ${{ vars.WORK_DATABASE_ID }}
    HONORS_DATABASE_ID: ${{ vars.HONORS_DATABASE_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build and export
        run: npm run build && npm run export
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: out/
